server:
  port: 8000

spring:
  application:
    name: finance-service
  config:
    import: "optional:configserver:"
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/finance?allowPublicKeyRetrieval=true&sslMode=DISABLED
    username: root
    password: infinito181019